### ISSUE TITLE
Improve docs and and scripts around setting up a developer environment

### ISSUE THREAD

**Issue by phildini** [debexpo/debexpo#1]
Right now, for me, this means a Vagrantfile.

Also going over the readme and seeing what could be clearer.

**Comment by paulproteus** [comment]
Glad you're thinking about this.

The README probably should link to the installation doc on readthedocs, and then we should focus on that, in my opinion.

**Comment by eeshangarg** [comment]
Hi @paulproteus, @phildini!

Yesterday, I was going through our installation docs, and I was thinking, should we recommend setting up a development environment as root? I did this yesterday on my Debian 8 Jessie workstation and it messed up my whole Python environment, in a way that I could not "workon" any of my virtualenvs after that, whenever I tried to switch to a virtualenv, I got an ugly error message about permissions being denied to access some random file that it needed to change environments. Plus, while setting up a dev environment as root, most (if not all) commands mentioned in the installation guide require superuser privileges (this is on my Debian 8 computer), but I don't know if this is something to worry about or not. I was able to fix my Python environment after a series of hasty workarounds, but I would not like other people to have to go through this. :-)

I can be wrong about this (please correct me if I am!), but would it not be better if we refine our instructions for setting up a debexpo virtualenv and for vagrant and not recommend setting up a dev enrivonment as root? Or, would it be possible to keep/limit the amount of packages you have to install (using apt-get) globally to an absolute minimum and perhaps then we could come up with a solution similar to OpenHatch's vendor directory so prospective contributors can just do a few essential apt-get installs and be able to run a development server right away? :-)

Let me know what you think!

Regards,
Eeshan

**Comment by phildini** [comment]
I think the line about root may have been a nod to those who prefer that setup. We should be encouraging an isolated dev environment wherever possible, whether that's weak isolation with virtualenv or strong isolation with vagrant. 

We should not list root as an option in the main list, I think, because the people who want to use that setup will already know how to translate the instructions for that setup.

/cc @paulproteus ?

**Comment by mapreri** [comment]
I'm closing this issue.  Yes, it probably needs more work (as IME all development setup processes do).  If anything it should be discussed in the form of merge requests though…
