### ISSUE TITLE
Set up staging server

### ISSUE THREAD

**Issue by phildini** [debexpo/debexpo#20]

**Comment by paulproteus** [comment]
It'd be nice to give this a *.debian.net domain name. I can try to do that.

debexpo-staging.debian.net ?

**Comment by paulproteus** [comment]
I just created `debexpo-staging.debian.net` and pointed it at 104.236.158.182. It might take the Debian DNS servers ~30 min to update with this, but email confirmation already came back to me from db.debian.org so I believe it's already in progress.

**Comment by paulproteus** [comment]
Yay! Already active in Debian's DNS servers:

```
➜  ~  host debexpo-staging.debian.net dns1.easydns.com
Using domain server:
Name: dns1.easydns.com
Address: 64.68.192.210#53
Aliases: 

debexpo-staging.debian.net has address 104.236.158.182
```

As context, dns1.easydns.com comes from:

```
➜  ~  whois debian.net | grep -i 'Name Server'
   Name Server: DNS1.EASYDNS.COM
   Name Server: DNS4.EASYDNS.INFO
   Name Server: SEC1.RCODE0.NET
   Name Server: SEC2.RCODE0.NET
Name Server: DNS1.EASYDNS.COM
Name Server: DNS4.EASYDNS.INFO
Name Server: SEC1.RCODE0.NET
Name Server: SEC2.RCODE0.NET
Name Server: 
Name Server: 
Name Server: 
Name Server: 
Name Server: 
Name Server: 
```

**Comment by paulproteus** [comment]
I just installed `nginx` on the staging server, and configured it to redirect all inbound HTTP requests (on port 80) to http://debexpo-staging.debian.net:5000/ .

I also installed `etckeeper` so we can see a git log of changes in `/etc`.

**Comment by paulproteus** [comment]
I think the only thing left to do is auto-update. I'll leave that to you.

**Comment by phildini** [comment]
Ah! Roger, roger.

**Comment by paulproteus** [comment]
https://github.com/debexpo/debexpo-management-scripts has scripts that handle auto-update.

I believe this is done, so I'm going to mark as resolved.

Props to you @phildini for making it work!
