### ISSUE TITLE
Setup syncing between alioth and github

### ISSUE THREAD

**Issue by phildini** [debexpo/debexpo#6]
I know this has already been started, but an issue for tracking purposes seems reasonable.

Also, I had some questions:
- There seems to be a branch on alioth that was more recently updated than master. (http://anonscm.debian.org/cgit/debexpo/debexpo.git/log/?h=live) Will we be pulling this in?
- How frequently will the sync run?
- What will happen in the (arguably unlikely case) someone adds code to alioth? Will the sync work both ways?

Thanks!

**Comment by paulproteus** [comment]
Thanks for filing this! I think here are my answers:

* For "live" -- yeah, we should integrate that into our development. This is what's currently live on the servers.

* How frequently will the sync run? I am thinking a combination of hourly+pinged by github web hooks.

* If someone adds code to Alioth, I imagine I'll configure the mirror script to either push it back to github, or to at least email me.

http://gitolite.com/gitolite/mirroring.html is a full-service replication thing I could possibly deploy. I was thinking of going for a smaller set of scripts that I write, with their own hand-made undiscovered bugginesses. Hmm.

**Comment by phildini** [comment]
Without giving the docs the full look that I should, gitolite seems reasonable, but it's (possibly) also reasonable to write your own scripts.

- Live should be merged into master, methinks. 
- would it make sense to notify the mailing list for things like PRs, merges, or the sync script running? I worry about signal-to-noise, but maybe it's useful?

**Comment by paulproteus** [comment]
re: live should be merged into master: should do that. I propose you.

re: notify mailing list for PRs, merges, sync script: You are correct that it shouldn't be to me personally, but at least to a group of some kind, even if I'm the only subscriber. My proposal goes against the Principle of Transparency (OK I capitalized it but I just made it up right now) for free software projects.

**Comment by paulproteus** [comment]
This is "done" for now.

What we do now is run https://github.com/debexpo/alioth-sync-scripts via an `@hourly` cron job, and it pushes state to Alioth.

It updates a little image, too. You can see that on the README.rst of the debexpo repo.

If we need more features for the sync, we can file a new issue for the specific changes to be made.
